### ISSUE TITLE
Jack throws errors upon exiting

### ISSUE THREAD

**Issue by themaxw** [tu-studio/audio-matrix#3]
Steps to reproduce:
- start jackd: `jackd -d dummy`
- start audiomatrix `audio-matrix -c /path/to/config.yml`
- stop audio-matrix using ctrl+C.

Then the same error messages start looping in the output of jackd:
```
JackLinuxFutex::Signal name = jack_sem.1000_default_jack_client already deallocated!!
JackFreewheelDriver::ProcessReadAsync: ResumeRefNum error
JackAudioDriver::ProcessGraphAsyncMaster: ProcessReadSlaves error
JackAudioDriver::ProcessGraphAsyncMaster: Process error
```
jackd version 1.9.21

**Comment by wax-m** [comment]
This was fixed by removing the explicit call to JackClient.prepare() from the main, and registering the callback for samplerate first (which immediately calls the  callback).
This way the jack client is only activated once
